### ISSUE TITLE
How to use these files

### ISSUE THREAD

**Issue by htnabe** [Frimkron/mid2rmba#1]
I recently bought a Roomba780 and I am planning to play MIDI file on the Roomba, but Idk how to use `mid2rmba.py` b/c I am not familiar with python files... Would you write how to use the file?

**Comment by Frimkron** [comment]
Hi htnabe, thanks for your message :)

I don't know how much you know about programming the Roomba already, but it looks like a good place to start would be this page: http://www.robotappstore.com/Knowledge-Base/1-Introduction-to-Roomba-Programming/15.html. Essentially you can send command codes to the Roomba to operate it programmatically, and there are codes to program and play very simple melodies.

So, some things to note:

* The number of notes the Roomba can store is extremely limited - it's really only designed to play simple "chimes" or "jingles" to, for example, indicate when it's completed a task.
* This python script I wrote just produces the raw command codes to be sent to the Roomba - it doesn't actually program the Roomba itself. You will need to follow a guide from the link above.
* I don't own a Roomba myself - I wrote this script for a friend and so I can't really guarantee that it will be compatible with your model, or even that it works at all. Consider it experimental.
* I wrote it for the Bash shell in Linux, so your mileage may vary on Mac or Windows

But with those caveats out of the way, here's how to install it:

1. `git checkout` the repository or download and extract the tarball
2. Install Python 3 and `pip`
3. Optionally, set up a [virtualenv](https://docs.python-guide.org/dev/virtualenvs/)
4. install the requirements with `pip install -r requirements.txt`. You might need to use `sudo`
5. test that the script is working by running `python mid2rmba.py -h`. It should display the command help.

Now, to use it to convert a short MIDI file called `mytune.mid`, and save the raw command bytes to `mytune.dat`:

```
python mid2rmba.py --outfile mytune.dat --tofmt bytes mytune.mid
```

Add the `--play` option to play a preview of the result. If the result is too fast or too slow, add the `--tempo` option to adjust it by a scale factor. You will probably also need to use a combination of the `--intro` and `--channel` options to extract the part of the MIDI tune that you actually want.
